## Deep learning classification model, using tabular input data
## Now including Keras' ModelCheckpoint method

In [1]:
# Sect 19.6.1 (rerun of Sect 19.4.2)

# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
attrition_df = pd.read_csv('HR-Employee-Attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [2]:
# Generate our categorical variable names list
attrition_cat = attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()

In [3]:
attrition_cat

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

In [4]:
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [5]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns = enc.get_feature_names(attrition_cat)
encode_df.head()

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [6]:
# Merge one-hot encoded features and drop the originals
attrition_df = attrition_df.merge(encode_df,left_index=True, right_index=True)
attrition_df = attrition_df.drop(attrition_cat,1)
attrition_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [7]:
# To separate features and target, as well as perform training/test split

# Split our preprocessed data into our features and target arrays
y = attrition_df["Attrition_Yes"].values
X = attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [8]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [9]:
# Sect 19.4.4 DL Model Design

# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 8)                 448
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 45
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6
=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [14]:
# Import checkpoint dependencies
import os
from tensorflow.keras.callbacks import ModelCheckpoint

# Define the checkpoint path and filenames
os.makedirs("checkpoints/",exist_ok=True)
checkpoint_path = "checkpoints/weights.{epoch:02d}.hdf5"

In [15]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Create a callback that saves the model's weights every 5 epochs
cp_callback = ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    save_weights_only=True,
    save_freq=1000)

# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100,callbacks=[cp_callback])

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Epoch 1/100
35/35 [==============================] - 0s 826us/step - loss: 0.1467 - accuracy: 0.9492
Epoch 2/100
35/35 [==============================] - 0s 883us/step - loss: 0.1425 - accuracy: 0.9501
Epoch 3/100
35/35 [==============================] - 0s 855us/step - loss: 0.1416 - accuracy: 0.9519
Epoch 4/100
35/35 [==============================] - 0s 912us/step - loss: 0.1401 - accuracy: 0.9519
Epoch 5/100
35/35 [==============================] - 0s 940us/step - loss: 0.1387 - accuracy: 0.9555
Epoch 6/100
35/35 [==============================] - 0s 826us/step - loss: 0.1379 - accuracy: 0.9528
Epoch 7/100
35/35 [==============================] - 0s 798us/step - loss: 0.1375 - accuracy: 0.9537
Epoch 8/100
35/35 [==============================] - 0s 855us/step - loss: 0.1366 - accuracy: 0.9501
Epoch 9/100
35/35 [==============================] - 0s 798us/step - loss: 0.1360 - accuracy: 0.9592
Epoch 10/100
35/35 [==============================] - 0s 826us/step - loss: 0.1347 - accuracy: 0.9510
Epoch 11/100
35/35 [==============================] - 0s 826us/step - loss: 0.1332 - accuracy: 0.9583
Epoch 12/100
35/35 [==============================] - 0s 855us/step - loss: 0.1325 - accuracy: 0.9574
Epoch 13/100
35/35 [==============================] - 0s 997us/step - loss: 0.1314 - accuracy: 0.9555
Epoch 14/100
35/35 [==============================] - 0s 997us/step - loss: 0.1300 - accuracy: 0.9555
Epoch 15/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1289 - accuracy: 0.9583
Epoch 16/100
35/35 [==============================] - 0s 912us/step - loss: 0.1292 - accuracy: 0.9555
Epoch 17/100
35/35 [==============================] - 0s 997us/step - loss: 0.1272 - accuracy: 0.9574
Epoch 18/100
35/35 [==============================] - 0s 912us/step - loss: 0.1267 - accuracy: 0.9564
Epoch 19/100
35/35 [==============================] - 0s 940us/step - loss: 0.1251 - accuracy: 0.9592
Epoch 20/100
35/35 [==============================] - 0s 855us/step - loss: 0.1244 - accuracy: 0.9564
Epoch 21/100
35/35 [==============================] - 0s 855us/step - loss: 0.1235 - accuracy: 0.9574
Epoch 22/100
35/35 [==============================] - 0s 855us/step - loss: 0.1222 - accuracy: 0.9601
Epoch 23/100
35/35 [==============================] - 0s 883us/step - loss: 0.1220 - accuracy: 0.9564
Epoch 24/100
35/35 [==============================] - 0s 912us/step - loss: 0.1205 - accuracy: 0.9592
Epoch 25/100
35/35 [==============================] - 0s 912us/step - loss: 0.1197 - accuracy: 0.9601
Epoch 26/100
35/35 [==============================] - 0s 855us/step - loss: 0.1184 - accuracy: 0.9601
Epoch 27/100
35/35 [==============================] - 0s 855us/step - loss: 0.1187 - accuracy: 0.9610
Epoch 28/100
35/35 [==============================] - 0s 883us/step - loss: 0.1173 - accuracy: 0.9592
Epoch 29/100
 1/35 [..............................] - ETA: 0s - loss: 0.1281 - accuracy: 0.9062
Epoch 00029: saving model to checkpoints\weights.29.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1164 - accuracy: 0.9583
Epoch 30/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1154 - accuracy: 0.9592
Epoch 31/100
35/35 [==============================] - 0s 969us/step - loss: 0.1145 - accuracy: 0.9610
Epoch 32/100
35/35 [==============================] - 0s 969us/step - loss: 0.1138 - accuracy: 0.9583
Epoch 33/100
35/35 [==============================] - 0s 969us/step - loss: 0.1136 - accuracy: 0.9610
Epoch 34/100
35/35 [==============================] - 0s 969us/step - loss: 0.1135 - accuracy: 0.9601
Epoch 35/100
35/35 [==============================] - 0s 883us/step - loss: 0.1120 - accuracy: 0.9610
Epoch 36/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1107 - accuracy: 0.9628
Epoch 37/100
35/35 [==============================] - 0s 883us/step - loss: 0.1104 - accuracy: 0.9628
Epoch 38/100
35/35 [==============================] - 0s 855us/step - loss: 0.1095 - accuracy: 0.9619
Epoch 39/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1085 - accuracy: 0.9601
Epoch 40/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1074 - accuracy: 0.9619
Epoch 41/100
35/35 [==============================] - 0s 912us/step - loss: 0.1077 - accuracy: 0.9646
Epoch 42/100
35/35 [==============================] - 0s 997us/step - loss: 0.1066 - accuracy: 0.9610
Epoch 43/100
35/35 [==============================] - 0s 826us/step - loss: 0.1058 - accuracy: 0.9619
Epoch 44/100
35/35 [==============================] - 0s 883us/step - loss: 0.1047 - accuracy: 0.9646
Epoch 45/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1044 - accuracy: 0.9619
Epoch 46/100
35/35 [==============================] - 0s 969us/step - loss: 0.1030 - accuracy: 0.9655
Epoch 47/100
35/35 [==============================] - 0s 826us/step - loss: 0.1022 - accuracy: 0.9637
Epoch 48/100
35/35 [==============================] - 0s 826us/step - loss: 0.1015 - accuracy: 0.9637
Epoch 49/100
35/35 [==============================] - 0s 855us/step - loss: 0.1013 - accuracy: 0.9655
Epoch 50/100
35/35 [==============================] - 0s 883us/step - loss: 0.1006 - accuracy: 0.9637
Epoch 51/100
35/35 [==============================] - 0s 883us/step - loss: 0.0989 - accuracy: 0.9673
Epoch 52/100
35/35 [==============================] - 0s 1ms/step - loss: 0.0988 - accuracy: 0.9673
Epoch 53/100
35/35 [==============================] - 0s 997us/step - loss: 0.0986 - accuracy: 0.9673
Epoch 54/100
35/35 [==============================] - 0s 1ms/step - loss: 0.0972 - accuracy: 0.9664
Epoch 55/100
35/35 [==============================] - 0s 1ms/step - loss: 0.0958 - accuracy: 0.9682
Epoch 56/100
35/35 [==============================] - 0s 1ms/step - loss: 0.0957 - accuracy: 0.9701
Epoch 57/100
35/35 [==============================] - 0s 1ms/step - loss: 0.0942 - accuracy: 0.9701
Epoch 58/100
 1/35 [..............................] - ETA: 0s - loss: 0.0738 - accuracy: 1.0000
Epoch 00058: saving model to checkpoints\weights.58.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.0934 - accuracy: 0.9701
Epoch 59/100
35/35 [==============================] - 0s 883us/step - loss: 0.0929 - accuracy: 0.9682
Epoch 60/100
35/35 [==============================] - 0s 883us/step - loss: 0.0918 - accuracy: 0.9691
Epoch 61/100
35/35 [==============================] - 0s 940us/step - loss: 0.0915 - accuracy: 0.9710
Epoch 62/100
35/35 [==============================] - 0s 912us/step - loss: 0.0910 - accuracy: 0.9701
Epoch 63/100
35/35 [==============================] - 0s 883us/step - loss: 0.0909 - accuracy: 0.9719
Epoch 64/100
35/35 [==============================] - 0s 940us/step - loss: 0.0904 - accuracy: 0.9737
Epoch 65/100
35/35 [==============================] - 0s 798us/step - loss: 0.0889 - accuracy: 0.9719
Epoch 66/100
35/35 [==============================] - 0s 940us/step - loss: 0.0875 - accuracy: 0.9719
Epoch 67/100
35/35 [==============================] - 0s 1ms/step - loss: 0.0867 - accuracy: 0.9755
Epoch 68/100
35/35 [==============================] - 0s 2ms/step - loss: 0.0869 - accuracy: 0.9710
Epoch 69/100
35/35 [==============================] - 0s 1ms/step - loss: 0.0863 - accuracy: 0.9728
Epoch 70/100
35/35 [==============================] - 0s 712us/step - loss: 0.0864 - accuracy: 0.9737
Epoch 71/100
35/35 [==============================] - 0s 855us/step - loss: 0.0843 - accuracy: 0.9728
Epoch 72/100
35/35 [==============================] - 0s 883us/step - loss: 0.0835 - accuracy: 0.9737
Epoch 73/100
35/35 [==============================] - 0s 883us/step - loss: 0.0830 - accuracy: 0.9728
Epoch 74/100
35/35 [==============================] - 0s 912us/step - loss: 0.0823 - accuracy: 0.9728
Epoch 75/100
35/35 [==============================] - 0s 912us/step - loss: 0.0817 - accuracy: 0.9773
Epoch 76/100
35/35 [==============================] - 0s 940us/step - loss: 0.0814 - accuracy: 0.9746
Epoch 77/100
35/35 [==============================] - 0s 912us/step - loss: 0.0806 - accuracy: 0.9728
Epoch 78/100
35/35 [==============================] - 0s 855us/step - loss: 0.0801 - accuracy: 0.9773

Epoch 79/100
35/35 [==============================] - 0s 940us/step - loss: 0.0801 - accuracy: 0.9746
Epoch 80/100
35/35 [==============================] - 0s 826us/step - loss: 0.0791 - accuracy: 0.9755
Epoch 81/100
35/35 [==============================] - 0s 798us/step - loss: 0.0777 - accuracy: 0.9773
Epoch 82/100
35/35 [==============================] - 0s 798us/step - loss: 0.0782 - accuracy: 0.9755
Epoch 83/100
35/35 [==============================] - 0s 798us/step - loss: 0.0766 - accuracy: 0.9800
Epoch 84/100
35/35 [==============================] - 0s 798us/step - loss: 0.0757 - accuracy: 0.9773
Epoch 85/100
35/35 [==============================] - 0s 798us/step - loss: 0.0753 - accuracy: 0.9773
Epoch 86/100
 1/35 [..............................] - ETA: 0s - loss: 0.0461 - accuracy: 1.0000
Epoch 00086: saving model to checkpoints\weights.86.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.0747 - accuracy: 0.9764
Epoch 87/100
35/35 [==============================] - 0s 826us/step - loss: 0.0740 - accuracy: 0.9791
Epoch 88/100
35/35 [==============================] - 0s 826us/step - loss: 0.0734 - accuracy: 0.9791
Epoch 89/100
35/35 [==============================] - 0s 798us/step - loss: 0.0733 - accuracy: 0.9782
Epoch 90/100
35/35 [==============================] - 0s 769us/step - loss: 0.0722 - accuracy: 0.9809
Epoch 91/100
35/35 [==============================] - 0s 798us/step - loss: 0.0727 - accuracy: 0.9800
Epoch 92/100
35/35 [==============================] - 0s 855us/step - loss: 0.0718 - accuracy: 0.9800
Epoch 93/100
35/35 [==============================] - 0s 826us/step - loss: 0.0708 - accuracy: 0.9800
Epoch 94/100
35/35 [==============================] - 0s 798us/step - loss: 0.0709 - accuracy: 0.9773
Epoch 95/100
35/35 [==============================] - 0s 798us/step - loss: 0.0704 - accuracy: 0.9791
Epoch 96/100
35/35 [==============================] - 0s 1ms/step - loss: 0.0692 - accuracy: 0.9809
Epoch 97/100
35/35 [==============================] - 0s 769us/step - loss: 0.0687 - accuracy: 0.9782
Epoch 98/100
35/35 [==============================] - 0s 769us/step - loss: 0.0679 - accuracy: 0.9782
Epoch 99/100
35/35 [==============================] - 0s 798us/step - loss: 0.0677 - accuracy: 0.9800
Epoch 100/100
35/35 [==============================] - 0s 1ms/step - loss: 0.0670 - accuracy: 0.9809
12/12 - 0s - loss: 0.8168 - accuracy: 0.8397
Loss: 0.8167627453804016, Accuracy: 0.8396739363670349

In [17]:
# Testing the use of the Keras Sequential model's load_weights method to restore the model weights.

# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  8
hidden_nodes_layer2 = 5

nn_new = tf.keras.models.Sequential()

# First hidden layer
nn_new.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn_new.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn_new.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the model
nn_new.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Restore the model weights
nn_new.load_weights("checkpoints/weights.86.hdf5")

# Evaluate the model using the test data
model_loss, model_accuracy = nn_new.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 0.7546 - accuracy: 0.8478
Loss: 0.7546488046646118, Accuracy: 0.8478260636329651

## Hierarchical Data Format file, HDF5. Using the Keras Sequential model's save method to export the entire model.

In [18]:
# Export our model to HDF5 file
nn_new.save("trained_attrition.h5")

In [19]:
# Trying the saved h5 file to recreate and test for performance. 

# Import the model to a new object
nn_imported = tf.keras.models.load_model('trained_attrition.h5')

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_new.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - loss: 0.7546 - accuracy: 0.8478
Loss: 0.7546488046646118, Accuracy: 0.8478260636329651